<?php
// $Id$
/**
 * Implementation of hook_services_method_call().
 */
function gaservice_services_method_call($method_name, $args, $browsing = FALSE) {
  //  Copyright 2009 Google Inc. All Rights Reserved.
  $GA_ACCOUNT = variable_get('GA_for_mobile_account',NULL);
  if($GA_ACCOUNT!=NULL){
    include_once drupal_get_path('module','gaservice')."/ga_mod.php";

    $referer = $_SERVER["HTTP_REFERER"];
    $query = $_SERVER["QUERY_STRING"];
    $path = $method_name;

    if (empty($referer)) {
      $referer = "-";
    }
    
    trackPageView(urlencode($referer),$method_name,$GA_ACCOUNT,$utmdebug);
    
  }
}

/**
 * Implementation of hook_menu()
 */
function gaservice_menu(){
  $items['admin/settings/gaservice'] = array(
    'title' => t('Google Analytics Service'),
    'description' => t('Server side GA scrips'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gaservice_settings'),
    'access arguments' => array('administer Google Analytics Service'),
  );
  return $items;
}

/**
 * Menu callback to configure gaservice module settings.
 */
function gaservice_settings(){
  $form['GA_for_mobile_account'] = array(
    '#title' => t('Google Analytics for Mobile Account'),
    '#description' => t('Please setup the Google Analytics for Mobile account number. You can replace "UA-XX" with "MO-XX".'),
    '#type' => 'textfield',
    '#size' => '10',
    '#required' => TRUE,
    '#default_value'=>variable_get('GA_for_mobile_account',NULL),
  );
  return system_settings_form($form);
}
